---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-pong-api
  template:
    metadata:
      labels:
        app: ping-pong-api
    spec:
      containers:
      - name: ping-pong-api
        image: mdraju1980/ping-pong-api:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-api
spec:
  selector:
    app: ping-pong-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
